name: residential-electricity-load-profiles                                                                 
channels:
  - defaults
  - conda-forge
dependencies:     
  - jupyterlab
  - numpy=1.18.1                                             
  - pandas=1.0.3
  - scipy=1.4.1
  - scikit-learn=0.22.1
  - matplotlib=3.1.3
  - seaborn=0.10.0
  - pip=20.0.2
  - shap=0.35.0